apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo-headless
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      nodeSelector:
        role: mongodb
      containers:
        - name: mongo
          image: robotshop/rs-mongodb:2.1.0
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mongo-storage
              mountPath: /var/lib/mongo
              subPath: mongo
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc