apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql-headless
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeSelector:
        role: mysqldb
      containers:
        - name: mysql
          image: robotshop/rs-mysql-db:2.1.0
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
              subPath: mysql 
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc