apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-rabbit
  namespace: robot-shop
spec:
  podSelector:
    matchLabels:
      app: rabbit
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: dispatch
    - podSelector:
        matchLabels:
          app: payment
    ports:
    - protocol: TCP
      port: 5672