apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis-headless
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        role: rabbitredisdb
      containers:
        - name: redis
          image: redis:6.2-alpine
          ports:
            - containerPort: 5672
          volumeMounts:
            - name: redis-storage
              mountPath: /var/lib/data
              subPath: redis 
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc