apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbit
spec:
  serviceName: rabbit-headless
  replicas: 3
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      nodeSelector:
        role: db
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - rabbit
                topologyKey: kubernetes.io/hostname
      containers:
        - name: rabbit
          image: rabbitmq:3.8-management-alpine

          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "robot"
            - name: RABBITMQ_DEFAULT_PASS
              value: "roboshop"
            - name: RABBITMQ_DEFAULT_VHOST
              value: "/"

          ports:
            - containerPort: 5672
            - containerPort: 15672

          volumeMounts:
            - name: rabbit-storage
              mountPath: /var/lib/rabbitmq

      volumes:
        - name: rabbit-storage
          persistentVolumeClaim:
            claimName: rabbit-pvc
