apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbit
spec:
  serviceName: rabbit-headless
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      nodeSelector:
        role: rabbitredisdb

      containers:
        - name: rabbit
          image: rabbitmq:3.8-management-alpine

          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              value: "guest"
            - name: RABBITMQ_ERLANG_COOKIE
              value: "secretcookie"
            - name: RABBITMQ_NODENAME
              value: "rabbit@$(HOSTNAME)"

          ports:
            - containerPort: 5672
            - containerPort: 15672 

          volumeMounts:
            - name: rabbit-storage
              mountPath: /var/lib/rabbitmq
              subPath: rabbit

      volumes:
        - name: rabbit-storage
          persistentVolumeClaim:
            claimName: rabbit-pvc