apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbit
spec:
  serviceName: rabbit-headless
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      nodeSelector:
        role: rabbitredisdb
      containers:
        - name: rabbit
          image: rabbitmq:3.8-management-alpine
          ports:
            - containerPort: 5672
          volumeMounts:
            - name: rabbit-storage
              mountPath: /var/lib/rabbitmq
              subPath: rabbit 
      volumes:
        - name: rabbit-storage
          persistentVolumeClaim:
            claimName: rabbit-pvc