resources:
  - ../../base
  - ../../hpa
  - ../../security
patches:
  - path: patch-all-replicas.yaml
    target:
      kind: Deployment

  - path: patch-all-replicas.yaml
    target:
      kind: StatefulSet
  